### ISSUE TITLE
Mint apt handling of apt-mark auto/manual

### ISSUE THREAD

**Issue by ewangi** [linuxmint/mintsystem#90]
mintsystem: 8.3.9

/usr/local/bin/apt currently passes the deprecated _markauto_ command through to apt-mark but not the _auto_ command that has replaced it. This seems incongruous. The general handling of auto and manual results in the following situation:

auto: apt-mark accepts
markauto: apt mark accepts but deprecated; Mint apt accepts
manual: apt-mark accepts
unmarkauto: apt-mark accepts but deprecated
markmanual: Mint apt accepts

It would probably be useful to add aliases so that all of these are passed through.

**Comment by gm10** [comment]
> /usr/local/bin/apt currently passes the deprecated markauto command through to apt-mark but not the auto command that has replaced it. 

No, it doesn't. You either misread the code or you're looking at a modified or possibly old version (I don't know if it ever did that).

**Comment by ewangi** [comment]
No, you misread and/or misinterpreted the text of my issue. Only markauto and markmanual are passed through. Nothing else is handled (and thus blocked). Your pull request has nothing to do with this issue and shouldn't have been referenced - that would be considered spam in other contexts.

I'm looking at /usr/local/bin/apt in a fully up-to-date Mint 19 system.

`elif argcommand in ("markauto", "markmanual"):
    # apt-mark
    command = "apt-mark %s %s" % (argcommand[4:], argoptions)
`

**Comment by ewangi** [comment]
No, I do get what you are saying about the genericness of auto and manual, and admit you have a point. I understand the code: markauto and markmanual are passed through as auto and manual. That is not what I'm referring to though, it's how the person using Mint's version of apt sees things when framing their commands (i.e. at *this* side of the filter) when they are used to using apt-mark.

Frankly, if you don't mind me saying so, I think that accusing folk of misreading the code, looking at a modified/old version (and thus not believing me when I stated my version of mintsystem right from the off), and finally of not understanding the code, are very disrespectful of someone who merely made a comment on something they thought was incongruous. No wonder people shy away from contributing code and help. However, I do appreciate that you're not part of the Mint team so will not think anything negative of the team as a result of your comments.

**Comment by gm10** [comment]
No, I am not part of the team nor do I speak for them. I also experience you as hostile and we're hopefully both misunderstanding each other in that respect, so I won't dwell on it. The only reason I had replied was because I thought you were misunderstanding something based on your use of the term "passed through", which has a specific meaning. I now understand you were using it with a different meaning, in fact you only care about the commands available to the user of Mint's apt wrapper, not the commands actually getting executed (correct me if I got it wrong). 

I further understand you saying that the Mint user will expect an `apt auto` command to exist. I don't understand why - binary apt/apt-get never support this, that's why apt-mark was created - but I suggest we just leave it at that since I'm not the one you have to convince.

**Comment by gm10** [comment]
As long as you don't let my opinion hold you back from stating your case the best you can then that's fine as well. As to the rest: The risks of textual communication, no worries, but I'm sorry as well for causing the wrong impression. Have a nice day indeed.

**Comment by ewangi** [comment]
Deleting this issue in order not to further take up the time of the developers.
